name: Deploy static site to GitHub Pages

on:
  push:
    tags:
      - "*.*.*"

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Extract tag version
        run: |
          VERSION=${GITHUB_REF#refs/tags/}
          echo "APP_VERSION=$VERSION" >> $GITHUB_ENV
          echo "Version: $VERSION"
          
      - name: Debug tree
        run: |
          pwd
          ls -la
          find . -maxdepth 4 -type f -name "version.template.js" -print

      - name: Generate version.js
        run: |
          sed "s|__APP_VERSION__|${APP_VERSION}|g" js/version.template.js > js/version.js

      - uses: actions/upload-pages-artifact@v3
        with:
          path: .

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
